# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md
#  - blog/index.html

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

# Site settings
title: "A Magno's Blog"  # Add your site title
description: "Your site description"  # Add a description

# Uncomment and update these settings
header_pages:
  - index.md
  - about.md
  - blog/index.html

# Theme settings
style: dark # dark (default) or light
listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag
