version: '3'
services:
  site:
    build: .
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"  # for livereload
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache: 